/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import Model.Autor;
import Model.Libro;
import org.hibernate.Session;

public class App {
  

    public static void main(String[] args) {
        System.out.println("Hola");
        
        guardarAutoresConLibros();
            
        System.out.println("Adeu");
    }
    
    

    
    public static void guardarAutor(){
        Session sessio=HibernateUtil.getSessionFactory().getCurrentSession();
        sessio.beginTransaction();

        Autor a=new Autor("Cervantes", "España");
        sessio.save(a);
        
        sessio.getTransaction().commit();
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
     public static void guardarLibro(){
        Session sessio=HibernateUtil.getSessionFactory().getCurrentSession();
        sessio.beginTransaction();
        
        
        
        Libro l;
        l=new Libro("Chacal", "Espias");
        Autor a= new Autor("Frederik Forsyth", "UK");
        l.setElAutor(a);
        
        sessio.save(l);  // guardo el libro, NO el AUTOR
        
        sessio.getTransaction().commit();
    }
     
     
     
     
     
     
//     
     
       public static void guardarAutoresConLibros(){
        Session sessio=HibernateUtil.getSessionFactory().getCurrentSession();
        sessio.beginTransaction();
        
        Autor a=new Autor("George R.R. Martin", "EEUU");
        a.addLlibre(new Libro("Juego de Tronos", "Fantasia",a));
        a.addLlibre(new Libro("Choque de Reyes", "Fantasia",a));
        a.addLlibre(new Libro("Tormenta de Espadas", "Fantasia",a));
        a.addLlibre(new Libro("Festín de Cuervos", "Fantasia",a));
        
        sessio.save(a);
        
        sessio.getTransaction().commit();
    }
}
