/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _AD_Connectors;

public class App {

    public static void main(String[] args) {
        
        mySQLConnector connexio=new mySQLConnector();
        connexio.provarConnexio();
               
    }
}
